services:
  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    expose:
      - "3000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    expose:
      - "80"
    restart: unless-stopped