# Global scope: Workspace
# NOTE: If you are deploying this with Coolify, you should go to "Configuration > Advanced > Build" and DISABLE "Inject Build Args to Dockerfile". If you don't do this, Coolify will inject a "true" value to the ARG by default, breaking this build. If you want to still inject them, you should find a way to manually inject back the correct value (the exact same one defined right here).
ARG WORKSPACE=packages/web

# Stage 1: Dependencies
FROM node:lts-alpine AS deps
WORKDIR /app

# Note: Declaring it without a value makes it inherit the global ARG on top
ARG WORKSPACE

COPY package*.json ./

# Sadly, we still need to copy the other workspace's package.json even if we shouldn't needed, due to the NPM limitations discussed below (see "NOTES" comment, point 2). If we made the switch to pnpm for example, we could avoid all these manual copies of individual workspaces.
COPY packages/core/package*.json ./packages/core/
COPY packages/web/package*.json ./packages/web/
COPY packages/admin/package*.json ./packages/admin/

# NOTES:
# 1. In the build stage we get all dependencies, including devDependencies, since devDependencies are needed for the build step (e.g. TypeScript, bundlers, etc.)
# 2. Due to limitations in how npm handles workspaces, we need to run npm ci at the root level, not just in the workspace folder, to ensure all dependencies are correctly installed and linked. If we ever want to move to a more efficient approach, we could consider switch to pnpm, which supports this use case much better with "pnpm --filter=<workspace> deploy".
RUN npm ci

# Stage 2: Builder
FROM node:lts-alpine AS builder
WORKDIR /app

# Note: Declaring it without a value makes it inherit the global ARG on top
ARG WORKSPACE

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build -w ${WORKSPACE}

# Stage 3: Runner (Nginx Static Server)
FROM nginx:stable-alpine AS runner

# Note: Declaring it without a value makes it inherit the global ARG on top
ARG WORKSPACE

# Copy the static files generated by Astro (dist folder) to Nginx's default directory
COPY --from=builder /app/${WORKSPACE}/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]