services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    # NOTE: Only open the port to the host for testing! In production, you should use a reverse proxy instead of exposing the port directly.
    # ports:
    #   - "8080:80"
    restart: unless-stopped