services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama
    restart: unless-stopped
    tty: true
    pull_policy: always
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
