import { tryRemoveBaseUrlFromPath } from '@utils/url';

// IMPORTANT: Since Astro 6, we can no longer import server-side only modules like astro:i18n in client-side scripts.
// So we can no longer import this file directly in client-side scripts, since it depends on astro:i18n for some of its functions.
import { getRelativeLocaleUrl } from "astro:i18n";

export function getHomeHelperFn(locale: string) {
  return (path?: Parameters<typeof getRelativeLocaleUrl>[1], options?: Parameters<typeof getRelativeLocaleUrl>[2]) => getRelativeLocaleUrl(locale, path, options);
}
export type HomeHelper = ReturnType<typeof getHomeHelperFn>;

/**
 * Extracts the "clean" path, removing the base_url and the current locale.
 * Example: If you are in "/my-repo/es/objectives", it returns "objectives".
 * This is necessary to pass a generic path to getRelativeLocaleUrl.
 */
export function getPlainPathNoLocale(pathname: string, currentLocale: string): string {
  let path = pathname;

  // 1. Remove baseUrlPath if it exists (e.g., for deployments in subfolders like GitHub Pages)
  path = tryRemoveBaseUrlFromPath(path);

  // 2. Remove the current locale from the URL
  const localeRegex = new RegExp(`^/${currentLocale}(/|$)`);
  path = path.replace(localeRegex, '/');

  // 3. Clean up leading/trailing slashes to leave the pure path string
  return path.replace(/^\/|\/$/g, '');
}

/**
 * Generates the absolute URL required for the hreflang tags.
 * Combines the site domain with the relative path generated by astro:i18n.
 */
export function getAbsoluteLocaleUrlFromOrigin(origin: string, targetLocale: string, plainPath: string): string {
  // getRelativeLocaleUrl automatically handles the baseUrl internally, 
  // so we just pass the target locale and the clean path.
  const relativePath = getRelativeLocaleUrl(targetLocale, plainPath);
  
  // Native JS URL() safely combines the base domain with the relative path
  return new URL(relativePath, origin).href;
}