import { baseUrlPath } from '@utils/url';
import { locales } from '@languages';
import { getRelativeLocaleUrl } from "astro:i18n";

export type HomeHelper = (path?: Parameters<typeof getRelativeLocaleUrl>[1], options?: Parameters<typeof getRelativeLocaleUrl>[2]) => ReturnType<typeof getRelativeLocaleUrl>;

export function getHomeHelperFn(locale: string): HomeHelper {
  return (path, options) => getRelativeLocaleUrl(locale, path, options);
}

/**
 * Extracts the "clean" path, removing the base_url and the current locale.
 * Example: If you are in "/my-repo/es/objectives", it returns "objectives".
 * This is necessary to pass a generic path to getRelativeLocaleUrl.
 */
export function getPlainPathNoLocale(pathname: string, currentLocale: string): string {
  let path = pathname;

  // 1. Remove baseUrlPath if it exists (e.g., for deployments in subfolders like GitHub Pages)
  path = tryRemoveBaseUrlFromPath(path);

  // 2. Remove the current locale from the URL
  const localeRegex = new RegExp(`^/${currentLocale}(/|$)`);
  path = path.replace(localeRegex, '/');

  // 3. Clean up leading/trailing slashes to leave the pure path string
  return path.replace(/^\/|\/$/g, '');
}

/**
 * Extracts the locale from the given path. It checks if the path starts with any of the supported locales.
 * If it does, it returns that locale. If not, it returns null.
 * It also handles the case where the path might include the baseUrlPath (e.g., for deployments in subfolders like GitHub Pages) by first removing it before checking for locales.
 */
export function extractLocaleFromPath(path: string): string | null {
  // First, try to remove the baseUrlPath if it exists (e.g., for deployments in subfolders like GitHub Pages)
  const cleanPath = tryRemoveBaseUrlFromPath(path);

  // Check if the pathname starts with any of the supported locales
  return locales.find(locale => cleanPath === `/${locale}` || cleanPath.startsWith(`/${locale}/`)) || null;
}

/**
 * Remove {@link baseUrlPath} from the start of the path if it exists (e.g., for deployments in subfolders like GitHub Pages)
 */
function tryRemoveBaseUrlFromPath(path: string): string {
  if (baseUrlPath && path.startsWith(baseUrlPath)) {
    return path.slice(baseUrlPath.length);
  }
  return path;
}

/**
 * Generates the absolute URL required for the hreflang tags.
 * Combines the site domain with the relative path generated by astro:i18n.
 */
export function getAbsoluteLocaleUrlFromOrigin(origin: string, targetLocale: string, plainPath: string): string {
  // getRelativeLocaleUrl automatically handles the baseUrl internally, 
  // so we just pass the target locale and the clean path.
  const relativePath = getRelativeLocaleUrl(targetLocale, plainPath);
  
  // Native JS URL() safely combines the base domain with the relative path
  return new URL(relativePath, origin).href;
}