services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    # NOTE: Only open the port to the host for testing! In production, you should use a reverse proxy instead of exposing the port directly.
    # ports:
    #   - "3000:3000"
    restart: unless-stopped